default: &default
  adapter: postgresql
  encoding: unicode
  host: aws-0-us-east-1.pooler.supabase.com
  port: 5432
  username: postgres.jvrgcqhclfqylkqrbzuv
  password: dodBu5-sykqoc-keswyn
  database: postgres
  sslmode: require
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
